version: 1

google:
    apikey: ${GOOGLE_API_KEY}

services:
  threadPoolTaskExecutorConfig:
    allowCoreThreadTimeOut: false
    corePoolSize: 1
    keepAliveSeconds: 60
    maxPoolSize: 2147483647
    queueCapacity: 2147483647

  eventRegistrationServiceUri:
    scheme: https
    host: maps.googleapis.com
    port: 8080
    basePath: /maps/api/place/details/json?placeid={placeId}
    templateValues:
  eventPublicationServiceUri:
    scheme: https
    host: maps.googleapis.com
    port: 8080
    basePath: /maps/api/place/details/json?placeid={placeId}
    templateValues:
